# Generated by Django 4.2.2 on 2024-01-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_productitem_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='description',
        ),
    ]
