# Generated by Django 4.2.2 on 2024-01-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_rename_productitem_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('lastname', models.CharField(max_length=60, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
